export interface NavPage {
  slug: string;
  title: string;
}

export interface NavTopic {
  label: string;
  pages: NavPage[];
}

export const BOSS_PAGES: NavPage[] = [
  { slug: "boss-guide", title: "Boss Guide" },
  { slug: "boss-order", title: "Boss Order" },
  { slug: "boss-drops", title: "Boss Drops Index" },
  { slug: "bosses-by-area", title: "Bosses by Area" },
  { slug: "eveque", title: "Eveque" },
  { slug: "goblu", title: "Goblu" },
  { slug: "ultimate-sakapatate", title: "Ultimate Sakapatate" },
  { slug: "francois", title: "Francois" },
  { slug: "lampmaster", title: "Lampmaster" },
  { slug: "dualliste", title: "Dualliste" },
  { slug: "stalact", title: "Stalact" },
  { slug: "visages", title: "Visages" },
  { slug: "mask-keeper", title: "Mask Keeper" },
  { slug: "glissando", title: "Glissando" },
  { slug: "sirene", title: "Sirene" },
  { slug: "renoir", title: "Renoir" },
  { slug: "the-paintress", title: "The Paintress" },
  { slug: "creation", title: "Creation" },
  { slug: "thunder-eveque", title: "Thunder Eveque" },
  { slug: "frost-eveque", title: "Frost Eveque" },
  { slug: "flame-eveque", title: "Flame Eveque" },
  { slug: "matthieu-the-colossus", title: "Matthieu the Colossus" },
  { slug: "julien-tiny-head", title: "Julien Tiny Head" },
  { slug: "golgra", title: "Golgra" },
  { slug: "grosse-tete", title: "Grosse Tete" },
  { slug: "giant-sapling", title: "Giant Sapling" },
  { slug: "rocher", title: "Rocher" },
  { slug: "tisseur", title: "Tisseur" },
  { slug: "serpenphare", title: "Serpenphare" },
  { slug: "sprong", title: "Sprong" },
  { slug: "glaise", title: "Glaise" },
  { slug: "scavenger", title: "Scavenger" },
  { slug: "chromatic-ballet", title: "Chromatic Ballet" },
  { slug: "chromatic-gold-chevaliere", title: "Chromatic Gold Chevaliere" },
  { slug: "blanche", title: "Blanche" },
  { slug: "chromatic-abbest", title: "Chromatic Abbest" },
  { slug: "chromatic-bourgeon", title: "Chromatic Bourgeon" },
  { slug: "chromatic-bruler", title: "Chromatic Bruler" },
  { slug: "chromatic-chalier", title: "Chromatic Chalier" },
  { slug: "chromatic-danseuse", title: "Chromatic Danseuse" },
  { slug: "chromatic-gault", title: "Chromatic Gault" },
  { slug: "chromatic-greatsword-cultist", title: "Chromatic Greatsword Cultist" },
  { slug: "chromatic-hexga", title: "Chromatic Hexga" },
  { slug: "chromatic-jar", title: "Chromatic Jar" },
  { slug: "chromatic-lancelier", title: "Chromatic Lancelier" },
  { slug: "chromatic-luster", title: "Chromatic Luster" },
  { slug: "chromatic-orphelin", title: "Chromatic Orphelin" },
  { slug: "chromatic-ramasseur", title: "Chromatic Ramasseur" },
  { slug: "chromatic-troubadour", title: "Chromatic Troubadour" },
  { slug: "alicia", title: "Alicia" },
  { slug: "simon", title: "Simon" },
  { slug: "bertrand-big-hands", title: "Bertrand Big Hands" },
  { slug: "dominique-giant-feet", title: "Dominique Giant Feet" },
  { slug: "dominique-tiny-feet", title: "Dominique Tiny Feet" },
  { slug: "jovial-moissonneuse", title: "Jovial Moissonneuse" },
  { slug: "seething-boucheclier", title: "Seething Boucheclier" },
  { slug: "sorrowful-chapelier", title: "Sorrowful Chapelier" },
  { slug: "clair-obscur", title: "Clair Obscur" },
  { slug: "white-haired-man", title: "White-Haired Man" },
  { slug: "gargant", title: "Gargant" },
  { slug: "jar", title: "Jar" },
  { slug: "bourgeon", title: "Bourgeon" },
  { slug: "mime", title: "Mime" },
];

export const TOPICS: NavTopic[] = [
  {
    label: "Weapons",
    pages: [
      { slug: "noahram", title: "Noahram" },
      { slug: "lanceram", title: "Lanceram" },
      { slug: "verleso", title: "Verleso" },
      { slug: "abysseram", title: "Abysseram" },
      { slug: "sakaram", title: "Sakaram" },
      { slug: "chevalam", title: "Chevalam" },
      { slug: "dreameso", title: "Dreameso" },
      { slug: "gesam", title: "Gesam" },
      { slug: "liteso", title: "Liteso" },
      { slug: "nosaram", title: "Nosaram" },
      { slug: "sireso", title: "Sireso" },
      { slug: "cruleram", title: "Cruleram" },
      { slug: "glaceso", title: "Glaceso" },
      { slug: "contorso", title: "Contorso" },
      { slug: "dualiso", title: "Dualiso" },
      { slug: "corpeso", title: "Corpeso" },
      { slug: "danseso", title: "Danseso" },
      { slug: "gaulteram", title: "Gaulteram" },
      { slug: "tireso", title: "Tireso" },
      { slug: "blodam", title: "Blodam" },
      { slug: "confuso", title: "Confuso" },
      { slug: "delaram", title: "Delaram" },
      { slug: "demonam", title: "Demonam" },
      { slug: "seeram", title: "Seeram" },
      { slug: "simoso", title: "Simoso" },
      { slug: "cultam", title: "Cultam" },
      { slug: "lunerim", title: "Lunerim" },
      { slug: "angerim", title: "Angerim" },
      { slug: "braselim", title: "Braselim" },
      { slug: "choralim", title: "Choralim" },
      { slug: "lighterim", title: "Lighterim" },
      { slug: "painerim", title: "Painerim" },
      { slug: "benisim", title: "Benisim" },
      { slug: "betelim", title: "Betelim" },
      { slug: "chapelim", title: "Chapelim" },
      { slug: "elerim", title: "Elerim" },
      { slug: "coralim", title: "Coralim" },
      { slug: "potierim", title: "Potierim" },
      { slug: "redalim", title: "Redalim" },
      { slug: "snowim", title: "Snowim" },
      { slug: "deminerim", title: "Deminerim" },
      { slug: "kralim", title: "Kralim" },
      { slug: "saperim", title: "Saperim" },
      { slug: "trebuchim", title: "Trebuchim" },
      { slug: "colim", title: "Colim" },
      { slug: "lithelim", title: "Lithelim" },
      { slug: "scaverim", title: "Scaverim" },
      { slug: "troubadim", title: "Troubadim" },
      { slug: "maellum", title: "Maellum" },
      { slug: "barrier-breaker", title: "Barrier Breaker" },
      { slug: "battlum", title: "Battlum" },
      { slug: "duenum", title: "Duenum" },
      { slug: "facesum", title: "Facesum" },
      { slug: "glaisum", title: "Glaisum" },
      { slug: "jarum", title: "Jarum" },
      { slug: "medalum", title: "Medalum" },
      { slug: "mellarum", title: "Mellarum" },
      { slug: "sekarum", title: "Sekarum" },
      { slug: "veremum", title: "Veremum" },
      { slug: "volesterum", title: "Volesterum" },
      { slug: "yeverum", title: "Yeverum" },
      { slug: "brulerum", title: "Brulerum" },
      { slug: "chantenum", title: "Chantenum" },
      { slug: "seashellum", title: "Seashellum" },
      { slug: "stalum", title: "Stalum" },
      { slug: "plenum", title: "Plenum" },
      { slug: "clierum", title: "Clierum" },
      { slug: "chalium", title: "Chalium" },
      { slug: "tissenum", title: "Tissenum" },
      { slug: "lithum", title: "Lithum" },
      { slug: "scieleson", title: "Scieleson" },
      { slug: "hevasson", title: "Hevasson" },
      { slug: "litheson", title: "Litheson" },
      { slug: "minason", title: "Minason" },
      { slug: "moisson", title: "Moisson" },
      { slug: "ramasson", title: "Ramasson" },
      { slug: "garganon", title: "Garganon" },
      { slug: "gobluson", title: "Gobluson" },
      { slug: "algueron", title: "Algueron" },
      { slug: "blizzon", title: "Blizzon" },
      { slug: "guleson", title: "Guleson" },
      { slug: "tisseron", title: "Tisseron" },
      { slug: "bourgelon", title: "Bourgelon" },
      { slug: "sadon", title: "Sadon" },
      { slug: "chation", title: "Chation" },
      { slug: "corderon", title: "Corderon" },
      { slug: "lusteson", title: "Lusteson" },
      { slug: "rangeson", title: "Rangeson" },
      { slug: "charnon", title: "Charnon" },
      { slug: "direton", title: "Direton" },
      { slug: "martenon", title: "Martenon" },
      { slug: "monocaro", title: "Monocaro" },
      { slug: "fragaro", title: "Fragaro" },
      { slug: "brumaro", title: "Brumaro" },
      { slug: "boucharo", title: "Boucharo" },
      { slug: "ballaro", title: "Ballaro" },
      { slug: "chromaro", title: "Chromaro" },
      { slug: "joyaro", title: "Joyaro" },
      { slug: "grandaro", title: "Grandaro" },
      { slug: "urnaro", title: "Urnaro" },
      { slug: "nusaro", title: "Nusaro" },
      { slug: "sidaro", title: "Sidaro" },
    ],
  },
  {
    label: "Enemies & Nevrons",
    pages: [
      { slug: "abbest", title: "Abbest" },
      { slug: "aberration", title: "Aberration" },
      { slug: "ballet", title: "Ballet" },
      { slug: "benisseur", title: "Benisseur" },
      { slug: "boucheclier", title: "Boucheclier" },
      { slug: "braseleur", title: "Braseleur" },
      { slug: "bruler", title: "Bruler" },
      { slug: "catapult-sakapatate", title: "Catapult Sakapatate" },
      { slug: "ceramic-chevaliere", title: "Ceramic Chevaliere" },
      { slug: "chalier", title: "Chalier" },
      { slug: "chapelier", title: "Chapelier" },
      { slug: "chorale", title: "Chorale" },
      { slug: "clair", title: "Clair" },
      { slug: "contorsionniste", title: "Contorsionniste" },
      { slug: "cruler", title: "Cruler" },
      { slug: "danseuse", title: "Danseuse" },
      { slug: "demineur", title: "Demineur" },
      { slug: "echassier", title: "Echassier" },
      { slug: "gault", title: "Gault" },
      { slug: "gold-chevaliere", title: "Gold Chevaliere" },
      { slug: "greatsword-cultist", title: "Greatsword Cultist" },
      { slug: "hexga", title: "Hexga" },
      { slug: "lancelier", title: "Lancelier" },
      { slug: "lumiere-citizen", title: "Lumiere Citizen" },
      { slug: "luster", title: "Luster" },
      { slug: "moissonneuse", title: "Moissonneuse" },
      { slug: "noire", title: "Noire" },
      { slug: "obscur", title: "Obscur" },
      { slug: "orphelin", title: "Orphelin" },
      { slug: "pelerin", title: "Pelerin" },
      { slug: "petank", title: "Petank" },
      { slug: "portier", title: "Portier" },
      { slug: "potier", title: "Potier" },
      { slug: "ramasseur", title: "Ramasseur" },
      { slug: "ranger-sakapatate", title: "Ranger Sakapatate" },
      { slug: "reaper-cultist", title: "Reaper Cultist" },
      { slug: "robust-sakapatate", title: "Robust Sakapatate" },
      { slug: "sapling", title: "Sapling" },
      { slug: "steel-chevaliere", title: "Steel Chevaliere" },
      { slug: "troubadour", title: "Troubadour" },
      { slug: "veilleur", title: "Veilleur" },
      { slug: "volester", title: "Volester" },
    ],
  },
  { label: "All Bosses", pages: BOSS_PAGES },
  {
    label: "Areas & Locations",
    pages: [
      { slug: "locations", title: "All Locations" },
      { slug: "abbest-cave", title: "Abbest Cave" },
      { slug: "chosen-path", title: "Chosen Path" },
      { slug: "camp-guide", title: "Camp Guide" },
      { slug: "interactive-map", title: "Interactive Map" },
      { slug: "world-lore", title: "World & Story" },
      { slug: "spring-meadows", title: "Spring Meadows" },
  { slug: "flying-waters", title: "Flying Waters" },
  { slug: "stone-wave-cliffs", title: "Stone Wave Cliffs" },
  { slug: "gestral-village", title: "Gestral Village" },
  { slug: "ancient-sanctuary", title: "Ancient Sanctuary" },
  { slug: "the-continent", title: "the-continent" },
  { slug: "old-lumiere", title: "Old Lumiere" },
  { slug: "forgotten-battlefield", title: "Forgotten Battlefield" },
  { slug: "monocos-station", title: "Monoco's Station" },
  { slug: "yellow-harvest", title: "Yellow Harvest" },
  { slug: "frozen-hearts", title: "Frozen Hearts" },
  { slug: "crimson-forest", title: "Crimson Forest" },
  { slug: "coastal-cave", title: "Coastal Cave" },
  { slug: "flying-manor", title: "Act 2" },
  { slug: "the-crows", title: "Act 2" },
  { slug: "sinister-cave", title: "Act 2" },
  { slug: "the-monolith", title: "the-monolith" },
  { slug: "lumiere", title: "lumiere" },
  { slug: "the-reacher", title: "the-reacher" },
  { slug: "the-abyss", title: "the-abyss" },
  { slug: "renoirs-drafts", title: "renoirs-drafts" },
  { slug: "versos-drafts", title: "versos-drafts" },
  { slug: "endless-tower", title: "endless-tower" },
    ],
  },
  {
    label: "Combat & Builds",
    pages: [
      { slug: "damage-mechanics", title: "Damage Mechanics" },
      { slug: "character-stats", title: "Character Stats" },
      { slug: "how-to-parry", title: "How to Parry" },
      { slug: "best-pictos", title: "Best Pictos" },
      { slug: "best-weapons", title: "Best Weapons" },
      { slug: "best-builds", title: "Best Builds" },
      { slug: "build-maelle", title: "Maelle Build" },
      { slug: "build-verso", title: "Verso Build" },
      { slug: "build-lune", title: "Lune Build" },
      { slug: "weapons-tier-list", title: "Weapons Tier List" },
      { slug: "tier-list", title: "Tier List" },
    ],
  },
  {
    label: "Reference & Collectibles",
    pages: [
      { slug: "enemy-weaknesses", title: "Enemy Weaknesses" },
      { slug: "weapons-locations", title: "Weapons Locations" },
      { slug: "side-quests", title: "Side Quests" },
      { slug: "trophy-guide", title: "Trophy Guide" },
      { slug: "endings-explained", title: "Endings Explained" },
      { slug: "characters", title: "Characters" },
    ],
  },
  {
    label: "Walkthrough",
    pages: [
      { slug: "guide", title: "Beginner Guide" },
      { slug: "walkthrough", title: "Full Walkthrough" },
      { slug: "walkthrough-act-1", title: "Act 1 Walkthrough" },
    ],
  },
];

export function getTopicForSlug(slug: string): NavTopic | undefined {
  return TOPICS.find((t) => t.pages.some((p) => p.slug === slug));
}

export function isBossSlug(slug: string): boolean {
  return BOSS_PAGES.some((p) => p.slug === slug);
}
