export interface NavPage {
  slug: string;
  title: string;
}

export interface NavTopic {
  label: string;
  pages: NavPage[];
}

export const BOSS_PAGES: NavPage[] = [
  { slug: "boss-guide", title: "Boss Guide" },
  { slug: "boss-order", title: "Boss Order" },
  { slug: "boss-drops", title: "Boss Drops Index" },
  { slug: "bosses-by-area", title: "Bosses by Area" },
  { slug: "eveque", title: "Eveque" },
  { slug: "goblu", title: "Goblu" },
  { slug: "ultimate-sakapatate", title: "Ultimate Sakapatate" },
  { slug: "francois", title: "Francois" },
  { slug: "lampmaster", title: "Lampmaster" },
  { slug: "dualliste", title: "Dualliste" },
  { slug: "stalact", title: "Stalact" },
  { slug: "visages", title: "Visages" },
  { slug: "mask-keeper", title: "Mask Keeper" },
  { slug: "glissando", title: "Glissando" },
  { slug: "sirene", title: "Sirene" },
  { slug: "renoir", title: "Renoir" },
  { slug: "the-paintress", title: "The Paintress" },
  { slug: "creation", title: "Creation" },
  { slug: "thunder-eveque", title: "Thunder Eveque" },
  { slug: "frost-eveque", title: "Frost Eveque" },
  { slug: "flame-eveque", title: "Flame Eveque" },
  { slug: "matthieu-the-colossus", title: "Matthieu the Colossus" },
  { slug: "julien-tiny-head", title: "Julien Tiny Head" },
  { slug: "golgra", title: "Golgra" },
  { slug: "grosse-tete", title: "Grosse Tete" },
  { slug: "giant-sapling", title: "Giant Sapling" },
  { slug: "rocher", title: "Rocher" },
  { slug: "tisseur", title: "Tisseur" },
  { slug: "serpenphare", title: "Serpenphare" },
  { slug: "sprong", title: "Sprong" },
  { slug: "glaise", title: "Glaise" },
  { slug: "scavenger", title: "Scavenger" },
  { slug: "chromatic-ballet", title: "Chromatic Ballet" },
  { slug: "chromatic-gold-chevaliere", title: "Chromatic Gold Chevaliere" },
  { slug: "blanche", title: "Blanche" },
  { slug: "chromatic-abbest", title: "Chromatic Abbest" },
  { slug: "chromatic-bourgeon", title: "Chromatic Bourgeon" },
  { slug: "chromatic-bruler", title: "Chromatic Bruler" },
  { slug: "chromatic-chalier", title: "Chromatic Chalier" },
  { slug: "chromatic-danseuse", title: "Chromatic Danseuse" },
  { slug: "chromatic-gault", title: "Chromatic Gault" },
  { slug: "chromatic-greatsword-cultist", title: "Chromatic Greatsword Cultist" },
  { slug: "chromatic-hexga", title: "Chromatic Hexga" },
  { slug: "chromatic-jar", title: "Chromatic Jar" },
  { slug: "chromatic-lancelier", title: "Chromatic Lancelier" },
  { slug: "chromatic-luster", title: "Chromatic Luster" },
  { slug: "chromatic-orphelin", title: "Chromatic Orphelin" },
  { slug: "chromatic-ramasseur", title: "Chromatic Ramasseur" },
  { slug: "chromatic-troubadour", title: "Chromatic Troubadour" },
  { slug: "alicia", title: "Alicia" },
  { slug: "simon", title: "Simon" },
  { slug: "bertrand-big-hands", title: "Bertrand Big Hands" },
  { slug: "dominique-giant-feet", title: "Dominique Giant Feet" },
  { slug: "dominique-tiny-feet", title: "Dominique Tiny Feet" },
  { slug: "jovial-moissonneuse", title: "Jovial Moissonneuse" },
  { slug: "seething-boucheclier", title: "Seething Boucheclier" },
  { slug: "sorrowful-chapelier", title: "Sorrowful Chapelier" },
  { slug: "clair-obscur", title: "Clair Obscur" },
  { slug: "white-haired-man", title: "White-Haired Man" },
  { slug: "gargant", title: "Gargant" },
  { slug: "jar", title: "Jar" },
  { slug: "bourgeon", title: "Bourgeon" },
  { slug: "mime", title: "Mime" },
];

export const TOPICS: NavTopic[] = [
  {
    label: "Pictos & Lumina",
    pages: [
      { slug: "accelerating-heal", title: "Accelerating Heal" },
      { slug: "accelerating-last-stand", title: "Accelerating Last Stand" },
      { slug: "accelerating-shots", title: "Accelerating Shots" },
      { slug: "accelerating-tint", title: "Accelerating Tint" },
      { slug: "aegis-revival", title: "Aegis Revival" },
      { slug: "alternating-critical", title: "Alternating Critical" },
      { slug: "anti-blight", title: "Anti-Blight" },
      { slug: "anti-burn", title: "Anti-Burn" },
      { slug: "anti-charm", title: "Anti-Charm" },
      { slug: "anti-freeze", title: "Anti-Freeze" },
      { slug: "anti-stun", title: "Anti-Stun" },
      { slug: "ap-discount", title: "AP Discount" },
      { slug: "at-death-s-door", title: "At Death's Door" },
      { slug: "attack-lifesteal", title: "Attack Lifesteal" },
      { slug: "augmented-aim", title: "Augmented Aim" },
      { slug: "augmented-attack", title: "Augmented Attack" },
      { slug: "augmented-counter-i", title: "Augmented Counter I" },
      { slug: "augmented-counter-ii", title: "Augmented Counter II" },
      { slug: "augmented-counter-iii", title: "Augmented Counter III" },
      { slug: "augmented-first-strike", title: "Augmented First Strike" },
      { slug: "auto-death", title: "Auto Death" },
      { slug: "auto-powerful", title: "Auto Powerful" },
      { slug: "auto-regen", title: "Auto Regen" },
      { slug: "auto-rush", title: "Auto Rush" },
      { slug: "auto-shell", title: "Auto Shell" },
      { slug: "base-shield", title: "Base Shield" },
      { slug: "beneficial-contamination", title: "Beneficial Contamination" },
      { slug: "break-specialist", title: "Break Specialist" },
      { slug: "breaker", title: "Breaker" },
      { slug: "breaking-attack", title: "Breaking Attack" },
      { slug: "breaking-burn", title: "Breaking Burn" },
      { slug: "breaking-counter", title: "Breaking Counter" },
      { slug: "breaking-death", title: "Breaking Death" },
      { slug: "breaking-shots", title: "Breaking Shots" },
      { slug: "burn-affinity", title: "Burn Affinity" },
      { slug: "burning-death", title: "Burning Death" },
      { slug: "burning-mark", title: "Burning Mark" },
      { slug: "burning-shots", title: "Burning Shots" },
      { slug: "charging-alteration", title: "Charging Alteration" },
      { slug: "charging-attack", title: "Charging Attack" },
      { slug: "charging-burn", title: "Charging Burn" },
      { slug: "charging-counter", title: "Charging Counter" },
      { slug: "charging-critical", title: "Charging Critical" },
      { slug: "charging-mark", title: "Charging Mark" },
      { slug: "charging-stun", title: "Charging Stun" },
      { slug: "charging-tint", title: "Charging Tint" },
      { slug: "charging-weakness", title: "Charging Weakness" },
      { slug: "cheater", title: "Cheater" },
      { slug: "clea-s-death", title: "Clea's Death" },
      { slug: "clea-s-life", title: "Clea's Life" },
      { slug: "cleansing-tint", title: "Cleansing Tint" },
      { slug: "combo-attack-i", title: "Combo Attack I" },
      { slug: "combo-attack-ii", title: "Combo Attack II" },
      { slug: "combo-attack-iii", title: "Combo Attack III" },
      { slug: "confident", title: "Confident" },
      { slug: "confident-fighter", title: "Confident Fighter" },
      { slug: "consuming-attack", title: "Consuming Attack" },
      { slug: "critical-break", title: "Critical Break" },
      { slug: "critical-burn", title: "Critical Burn" },
      { slug: "critical-moment", title: "Critical Moment" },
      { slug: "critical-stun", title: "Critical Stun" },
      { slug: "critical-vulnerability", title: "Critical Vulnerability" },
      { slug: "critical-weakness", title: "Critical Weakness" },
      { slug: "damage-share", title: "Damage Share" },
      { slug: "dead-energy-i", title: "Dead Energy I" },
      { slug: "dead-energy-ii", title: "Dead Energy II" },
      { slug: "death-bomb", title: "Death Bomb" },
      { slug: "defensive-mode", title: "Defensive Mode" },
      { slug: "double-burn", title: "Double Burn" },
      { slug: "double-mark", title: "Double Mark" },
      { slug: "draining-cleanse", title: "Draining Cleanse" },
      { slug: "effective-heal", title: "Effective Heal" },
      { slug: "effective-support", title: "Effective Support" },
      { slug: "empowering-attack", title: "Empowering Attack" },
      { slug: "empowering-break", title: "Empowering Break" },
      { slug: "empowering-dodge", title: "Empowering Dodge" },
      { slug: "empowering-last-stand", title: "Empowering Last Stand" },
      { slug: "empowering-parry", title: "Empowering Parry" },
      { slug: "empowering-tint", title: "Empowering Tint" },
      { slug: "energising-attack-i", title: "Energising Attack I" },
      { slug: "energising-attack-ii", title: "Energising Attack II" },
      { slug: "energising-break", title: "Energising Break" },
      { slug: "energising-burn", title: "Energising Burn" },
      { slug: "energising-cleanse", title: "Energising Cleanse" },
      { slug: "energising-death", title: "Energising Death" },
      { slug: "energising-gradient", title: "Energising Gradient" },
      { slug: "energising-heal", title: "Energising Heal" },
      { slug: "energising-jump", title: "Energising Jump" },
      { slug: "energising-pain", title: "Energising Pain" },
      { slug: "energising-parry", title: "Energising Parry" },
      { slug: "energising-powerful", title: "Energising Powerful" },
      { slug: "energising-revive", title: "Energising Revive" },
      { slug: "energising-rush", title: "Energising Rush" },
      { slug: "energising-shell", title: "Energising Shell" },
      { slug: "energising-shots", title: "Energising Shots" },
      { slug: "energising-start-i", title: "Energising Start I" },
      { slug: "energising-start-ii", title: "Energising Start II" },
      { slug: "energising-start-iii", title: "Energising Start III" },
      { slug: "energising-start-iv", title: "Energising Start IV" },
      { slug: "energising-stun", title: "Energising Stun" },
      { slug: "energising-turn", title: "Energising Turn" },
      { slug: "energy-master", title: "Energy Master" },
      { slug: "enfeebling-attack", title: "Enfeebling Attack" },
      { slug: "enfeebling-mark", title: "Enfeebling Mark" },
      { slug: "exhausting-power", title: "Exhausting Power" },
      { slug: "exposing-attack", title: "Exposing Attack" },
      { slug: "exposing-break", title: "Exposing Break" },
      { slug: "faster-than-strong", title: "Faster Than Strong" },
      { slug: "first-offensive", title: "First Offensive" },
      { slug: "first-strike", title: "First Strike" },
      { slug: "fueling-break", title: "Fueling Break" },
      { slug: "full-strength", title: "Full Strength" },
      { slug: "glass-canon", title: "Glass Canon" },
      { slug: "gradient-break", title: "Gradient Break" },
      { slug: "gradient-breaker", title: "Gradient Breaker" },
      { slug: "gradient-fighter", title: "Gradient Fighter" },
      { slug: "greater-defenceless", title: "Greater Defenceless" },
      { slug: "greater-powerful", title: "Greater Powerful" },
      { slug: "greater-powerless", title: "Greater Powerless" },
      { slug: "greater-rush", title: "Greater Rush" },
      { slug: "greater-shell", title: "Greater Shell" },
      { slug: "greater-slow", title: "Greater Slow" },
      { slug: "healing-boon", title: "Healing Boon" },
      { slug: "healing-counter", title: "Healing Counter" },
      { slug: "healing-death", title: "Healing Death" },
      { slug: "healing-fire", title: "Healing Fire" },
      { slug: "healing-mark", title: "Healing Mark" },
      { slug: "healing-parry", title: "Healing Parry" },
      { slug: "healing-share", title: "Healing Share" },
      { slug: "healing-stun", title: "Healing Stun" },
      { slug: "healing-tint-energy", title: "Healing Tint Energy" },
      { slug: "in-medias-res", title: "In Medias Res" },
      { slug: "inverted-affinity", title: "Inverted Affinity" },
      { slug: "last-stand-critical", title: "Last Stand Critical" },
      { slug: "longer-burn", title: "Longer Burn" },
      { slug: "longer-powerful", title: "Longer Powerful" },
      { slug: "longer-rush", title: "Longer Rush" },
      { slug: "longer-shell", title: "Longer Shell" },
      { slug: "marking-break", title: "Marking Break" },
      { slug: "marking-shots", title: "Marking Shots" },
      { slug: "painted-power", title: "Painted Power" },
      { slug: "perilous-parry", title: "Perilous Parry" },
      { slug: "piercing-shot", title: "Piercing Shot" },
      { slug: "powered-attack", title: "Powered Attack" },
      { slug: "powerful-heal", title: "Powerful Heal" },
      { slug: "powerful-mark", title: "Powerful Mark" },
      { slug: "powerful-on-shell", title: "Powerful on Shell" },
      { slug: "powerful-revive", title: "Powerful Revive" },
      { slug: "powerful-shield", title: "Powerful Shield" },
      { slug: "powerful-shots", title: "Powerful Shots" },
      { slug: "pro-retreat", title: "Pro Retreat" },
      { slug: "protecting-attack", title: "Protecting Attack" },
      { slug: "protecting-death", title: "Protecting Death" },
      { slug: "protecting-heal", title: "Protecting Heal" },
      { slug: "protecting-last-stand", title: "Protecting Last Stand" },
      { slug: "protecting-tint", title: "Protecting Tint" },
      { slug: "quick-break", title: "Quick Break" },
      { slug: "random-defense", title: "Random Defense" },
      { slug: "rejuvenating-revive", title: "Rejuvenating Revive" },
      { slug: "revive-tint-energy", title: "Revive Tint Energy" },
      { slug: "rewarding-mark", title: "Rewarding Mark" },
      { slug: "rush-on-powerful", title: "Rush on Powerful" },
      { slug: "second-chance", title: "Second Chance" },
      { slug: "shared-care", title: "Shared Care" },
      { slug: "shell-on-rush", title: "Shell On Rush" },
      { slug: "shield-affinity", title: "Shield Affinity" },
      { slug: "shielding-death", title: "Shielding Death" },
      { slug: "shielding-tint", title: "Shielding Tint" },
      { slug: "slowing-break", title: "Slowing Break" },
      { slug: "solidifying", title: "Solidifying" },
      { slug: "solo-fighter", title: "Solo Fighter" },
      { slug: "sos-power", title: "SOS Power" },
      { slug: "sos-rush", title: "SOS Rush" },
      { slug: "sos-shell", title: "SOS Shell" },
      { slug: "staggering-attack", title: "Staggering Attack" },
      { slug: "stay-marked", title: "Stay Marked" },
      { slug: "stun-boost", title: "Stun Boost" },
      { slug: "sweet-kill", title: "Sweet Kill" },
      { slug: "tainted", title: "Tainted" },
      { slug: "teamwork", title: "Teamwork" },
      { slug: "the-one", title: "The One" },
      { slug: "time-tint", title: "Time Tint" },
      { slug: "versatile", title: "Versatile" },
      { slug: "warming-up", title: "Warming Up" },
      { slug: "weakness-gain", title: "Weakness Gain" },
    ],
  },
  {
    label: "Weapons",
    pages: [
      { slug: "noahram", title: "Noahram" },
      { slug: "lanceram", title: "Lanceram" },
      { slug: "verleso", title: "Verleso" },
      { slug: "abysseram", title: "Abysseram" },
      { slug: "sakaram", title: "Sakaram" },
      { slug: "chevalam", title: "Chevalam" },
      { slug: "dreameso", title: "Dreameso" },
      { slug: "gesam", title: "Gesam" },
      { slug: "liteso", title: "Liteso" },
      { slug: "nosaram", title: "Nosaram" },
      { slug: "sireso", title: "Sireso" },
      { slug: "cruleram", title: "Cruleram" },
      { slug: "glaceso", title: "Glaceso" },
      { slug: "contorso", title: "Contorso" },
      { slug: "dualiso", title: "Dualiso" },
      { slug: "corpeso", title: "Corpeso" },
      { slug: "danseso", title: "Danseso" },
      { slug: "gaulteram", title: "Gaulteram" },
      { slug: "tireso", title: "Tireso" },
      { slug: "blodam", title: "Blodam" },
      { slug: "confuso", title: "Confuso" },
      { slug: "delaram", title: "Delaram" },
      { slug: "demonam", title: "Demonam" },
      { slug: "seeram", title: "Seeram" },
      { slug: "simoso", title: "Simoso" },
      { slug: "cultam", title: "Cultam" },
      { slug: "lunerim", title: "Lunerim" },
      { slug: "angerim", title: "Angerim" },
      { slug: "braselim", title: "Braselim" },
      { slug: "choralim", title: "Choralim" },
      { slug: "lighterim", title: "Lighterim" },
      { slug: "painerim", title: "Painerim" },
      { slug: "benisim", title: "Benisim" },
      { slug: "betelim", title: "Betelim" },
      { slug: "chapelim", title: "Chapelim" },
      { slug: "elerim", title: "Elerim" },
      { slug: "coralim", title: "Coralim" },
      { slug: "potierim", title: "Potierim" },
      { slug: "redalim", title: "Redalim" },
      { slug: "snowim", title: "Snowim" },
      { slug: "deminerim", title: "Deminerim" },
      { slug: "kralim", title: "Kralim" },
      { slug: "saperim", title: "Saperim" },
      { slug: "trebuchim", title: "Trebuchim" },
      { slug: "colim", title: "Colim" },
      { slug: "lithelim", title: "Lithelim" },
      { slug: "scaverim", title: "Scaverim" },
      { slug: "troubadim", title: "Troubadim" },
      { slug: "maellum", title: "Maellum" },
      { slug: "barrier-breaker", title: "Barrier Breaker" },
      { slug: "battlum", title: "Battlum" },
      { slug: "duenum", title: "Duenum" },
      { slug: "facesum", title: "Facesum" },
      { slug: "glaisum", title: "Glaisum" },
      { slug: "jarum", title: "Jarum" },
      { slug: "medalum", title: "Medalum" },
      { slug: "mellarum", title: "Mellarum" },
      { slug: "sekarum", title: "Sekarum" },
      { slug: "veremum", title: "Veremum" },
      { slug: "volesterum", title: "Volesterum" },
      { slug: "yeverum", title: "Yeverum" },
      { slug: "brulerum", title: "Brulerum" },
      { slug: "chantenum", title: "Chantenum" },
      { slug: "seashellum", title: "Seashellum" },
      { slug: "stalum", title: "Stalum" },
      { slug: "plenum", title: "Plenum" },
      { slug: "clierum", title: "Clierum" },
      { slug: "chalium", title: "Chalium" },
      { slug: "tissenum", title: "Tissenum" },
      { slug: "lithum", title: "Lithum" },
      { slug: "scieleson", title: "Scieleson" },
      { slug: "hevasson", title: "Hevasson" },
      { slug: "litheson", title: "Litheson" },
      { slug: "minason", title: "Minason" },
      { slug: "moisson", title: "Moisson" },
      { slug: "ramasson", title: "Ramasson" },
      { slug: "garganon", title: "Garganon" },
      { slug: "gobluson", title: "Gobluson" },
      { slug: "algueron", title: "Algueron" },
      { slug: "blizzon", title: "Blizzon" },
      { slug: "guleson", title: "Guleson" },
      { slug: "tisseron", title: "Tisseron" },
      { slug: "bourgelon", title: "Bourgelon" },
      { slug: "sadon", title: "Sadon" },
      { slug: "chation", title: "Chation" },
      { slug: "corderon", title: "Corderon" },
      { slug: "lusteson", title: "Lusteson" },
      { slug: "rangeson", title: "Rangeson" },
      { slug: "charnon", title: "Charnon" },
      { slug: "direton", title: "Direton" },
      { slug: "martenon", title: "Martenon" },
      { slug: "monocaro", title: "Monocaro" },
      { slug: "fragaro", title: "Fragaro" },
      { slug: "brumaro", title: "Brumaro" },
      { slug: "boucharo", title: "Boucharo" },
      { slug: "ballaro", title: "Ballaro" },
      { slug: "chromaro", title: "Chromaro" },
      { slug: "joyaro", title: "Joyaro" },
      { slug: "grandaro", title: "Grandaro" },
      { slug: "urnaro", title: "Urnaro" },
      { slug: "nusaro", title: "Nusaro" },
      { slug: "sidaro", title: "Sidaro" },
    ],
  },
  {
    label: "Enemies & Nevrons",
    pages: [
      { slug: "abbest", title: "Abbest" },
      { slug: "aberration", title: "Aberration" },
      { slug: "ballet", title: "Ballet" },
      { slug: "benisseur", title: "Benisseur" },
      { slug: "boucheclier", title: "Boucheclier" },
      { slug: "braseleur", title: "Braseleur" },
      { slug: "bruler", title: "Bruler" },
      { slug: "catapult-sakapatate", title: "Catapult Sakapatate" },
      { slug: "ceramic-chevaliere", title: "Ceramic Chevaliere" },
      { slug: "chalier", title: "Chalier" },
      { slug: "chapelier", title: "Chapelier" },
      { slug: "chorale", title: "Chorale" },
      { slug: "clair", title: "Clair" },
      { slug: "contorsionniste", title: "Contorsionniste" },
      { slug: "cruler", title: "Cruler" },
      { slug: "danseuse", title: "Danseuse" },
      { slug: "demineur", title: "Demineur" },
      { slug: "echassier", title: "Echassier" },
      { slug: "gault", title: "Gault" },
      { slug: "gold-chevaliere", title: "Gold Chevaliere" },
      { slug: "greatsword-cultist", title: "Greatsword Cultist" },
      { slug: "hexga", title: "Hexga" },
      { slug: "lancelier", title: "Lancelier" },
      { slug: "lumiere-citizen", title: "Lumiere Citizen" },
      { slug: "luster", title: "Luster" },
      { slug: "moissonneuse", title: "Moissonneuse" },
      { slug: "noire", title: "Noire" },
      { slug: "obscur", title: "Obscur" },
      { slug: "orphelin", title: "Orphelin" },
      { slug: "pelerin", title: "Pelerin" },
      { slug: "petank", title: "Petank" },
      { slug: "portier", title: "Portier" },
      { slug: "potier", title: "Potier" },
      { slug: "ramasseur", title: "Ramasseur" },
      { slug: "ranger-sakapatate", title: "Ranger Sakapatate" },
      { slug: "reaper-cultist", title: "Reaper Cultist" },
      { slug: "robust-sakapatate", title: "Robust Sakapatate" },
      { slug: "sapling", title: "Sapling" },
      { slug: "steel-chevaliere", title: "Steel Chevaliere" },
      { slug: "troubadour", title: "Troubadour" },
      { slug: "veilleur", title: "Veilleur" },
      { slug: "volester", title: "Volester" },
    ],
  },
  { label: "All Bosses", pages: BOSS_PAGES },
  {
    label: "Areas & Locations",
    pages: [
      { slug: "locations", title: "All Locations" },
      { slug: "abbest-cave", title: "Abbest Cave" },
      { slug: "chosen-path", title: "Chosen Path" },
      { slug: "camp-guide", title: "Camp Guide" },
      { slug: "interactive-map", title: "Interactive Map" },
      { slug: "world-lore", title: "World & Story" },
      { slug: "spring-meadows", title: "Spring Meadows" },
  { slug: "flying-waters", title: "Flying Waters" },
  { slug: "stone-wave-cliffs", title: "Stone Wave Cliffs" },
  { slug: "gestral-village", title: "Gestral Village" },
  { slug: "ancient-sanctuary", title: "Ancient Sanctuary" },
  { slug: "the-continent", title: "the-continent" },
  { slug: "old-lumiere", title: "Old Lumiere" },
  { slug: "forgotten-battlefield", title: "Forgotten Battlefield" },
  { slug: "monocos-station", title: "Monoco's Station" },
  { slug: "yellow-harvest", title: "Yellow Harvest" },
  { slug: "frozen-hearts", title: "Frozen Hearts" },
  { slug: "crimson-forest", title: "Crimson Forest" },
  { slug: "coastal-cave", title: "Coastal Cave" },
  { slug: "flying-manor", title: "Act 2" },
  { slug: "the-crows", title: "Act 2" },
  { slug: "sinister-cave", title: "Act 2" },
  { slug: "the-monolith", title: "the-monolith" },
  { slug: "lumiere", title: "lumiere" },
  { slug: "the-reacher", title: "the-reacher" },
  { slug: "the-abyss", title: "the-abyss" },
  { slug: "renoirs-drafts", title: "renoirs-drafts" },
  { slug: "versos-drafts", title: "versos-drafts" },
  { slug: "endless-tower", title: "endless-tower" },
    ],
  },
  {
    label: "Combat & Builds",
    pages: [
      { slug: "damage-mechanics", title: "Damage Mechanics" },
      { slug: "character-stats", title: "Character Stats" },
      { slug: "how-to-parry", title: "How to Parry" },
      { slug: "best-pictos", title: "Best Pictos" },
      { slug: "best-weapons", title: "Best Weapons" },
      { slug: "best-builds", title: "Best Builds" },
      { slug: "build-maelle", title: "Maelle Build" },
      { slug: "build-verso", title: "Verso Build" },
      { slug: "build-lune", title: "Lune Build" },
      { slug: "weapons-tier-list", title: "Weapons Tier List" },
      { slug: "tier-list", title: "Tier List" },
    ],
  },
  {
    label: "Reference & Collectibles",
    pages: [
      { slug: "enemy-weaknesses", title: "Enemy Weaknesses" },
      { slug: "weapons-locations", title: "Weapons Locations" },
      { slug: "side-quests", title: "Side Quests" },
      { slug: "trophy-guide", title: "Trophy Guide" },
      { slug: "endings-explained", title: "Endings Explained" },
      { slug: "characters", title: "Characters" },
    ],
  },
  {
    label: "Walkthrough",
    pages: [
      { slug: "guide", title: "Beginner Guide" },
      { slug: "walkthrough", title: "Full Walkthrough" },
      { slug: "walkthrough-act-1", title: "Act 1 Walkthrough" },
    ],
  },
];

export function getTopicForSlug(slug: string): NavTopic | undefined {
  return TOPICS.find((t) => t.pages.some((p) => p.slug === slug));
}

export function isBossSlug(slug: string): boolean {
  return BOSS_PAGES.some((p) => p.slug === slug);
}
